version: '3.1'
services: 
  node:
    build: './backend'
    networks:
      net:
        aliases:
          - node
    ports: 
      - "8080:8080"
    container_name: node
    hostname: node
  db:
    image: mongo:4.0
    restart: always
    networks:
      net:
        aliases:
          - db
    ports:
      - "27017:27017"
    container_name: db
    hostname: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: temperatures
    volumes:
      - ./backend/mongo-dump:/docker-entrypoint-initdb.d
    
  web: 
    build: './frontend'
    networks:
      net:
        aliases:
          - web    
    ports: 
      - "80:80" 
    container_name: web
    hostname: web    
networks:
  net:
    driver: bridge


