version: '3.1'
services: 
  node:
    build: .
    networks:
      net:
        aliases:
          - node
    ports: 
      - "8080:80"
    container_name: node
    hostname: node
  db:
    image: mongo:4.0
    restart: always
    networks:
      net:
        aliases:
          - db
    ports:
      - "27017:27017"
    container_name: db
    hostname: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  web: 
    
networks:
  net:
    driver: bridge


